-- Seed exercises into Supabase
-- These are system exercises (owner_id IS NULL) visible to all users

INSERT INTO exercises (id, name, category, muscle, equipment, difficulty, instructions, is_custom, owner_id)
VALUES
  ('bench', 'Bench Press', 'push', 'Klatka', 'Sztanga', 'intermediate',
   ARRAY['Poloz sie na lawce, stopy plasko na podlodze', 'Chwyć sztange szerzej niz biodra', 'Opuszczaj sztange do klatki kontrolowanym ruchem', 'Wypchnij do pelnego wyprostu ramion'],
   false, NULL),
  ('incline-bench', 'Incline Bench Press', 'push', 'Klatka (gorna)', 'Sztanga', 'intermediate',
   ARRAY['Ustaw lawke pod katem 30-45 stopni', 'Chwyć sztange szerzej niz biodra', 'Opuszczaj do gornej czesci klatki', 'Wypchnij do pelnego wyprostu'],
   false, NULL),
  ('ohp', 'Overhead Press', 'push', 'Barki', 'Sztanga', 'intermediate',
   ARRAY['Stoj prosto, sztanga na obojczykach', 'Chwyc sztange na szerokosc barkow', 'Wypchnij nad glowe do pelnego wyprostu', 'Opuszczaj kontrolowany do obojczykow'],
   false, NULL),
  ('dip', 'Weighted Dip', 'push', 'Klatka / Tricepsy', 'Poręcze', 'advanced',
   ARRAY['Chwyć poręcze, wyprostuj ramiona', 'Opuszczaj cialo az ramiona beda pod katem 90 stopni', 'Wypchnij do pelnego wyprostu'],
   false, NULL),
  ('tricep-pd', 'Tricep Pushdown', 'push', 'Tricepsy', 'Wyciąg', 'beginner',
   ARRAY['Stoj przodem do wyciagu, chwyc linki', 'Opuszczaj ramiona do pelnego wyprostu', 'Kontroluj powrot do pozycji poczatkowej'],
   false, NULL),
  ('squat', 'Back Squat', 'legs', 'Cwiczki / Posladki', 'Sztanga', 'intermediate',
   ARRAY['Sztanga na obojczykach, stopy na szerokosc bioder', 'Opuszczaj biodra do dolu jak na krzeslo', 'Utrzymuj klatke prosto', 'Wypchnij do pelnego wyprostu'],
   false, NULL),
  ('rdl', 'Romanian Deadlift', 'legs', 'Posladki', 'Sztanga', 'intermediate',
   ARRAY['Stoj prosto, sztanga przed biodrami', 'Pochylaj tułowiidol do przodu z prostymi plecami', 'Opuszczaj sztange blisko nog', 'Czuj napięcie w posladkach i udach'],
   false, NULL),
  ('leg-press', 'Leg Press', 'legs', 'Cwiczki', 'Maszyna', 'beginner',
   ARRAY['Usiasdz na maszynie, stopy na szerokosc bioder', 'Opuszczaj poraz az kolana beda pod katem 90 stopni', 'Wypchnij do pelnego wyprostu'],
   false, NULL),
  ('deadlift', 'Deadlift', 'pull', 'Plecy', 'Sztanga', 'advanced',
   ARRAY['Stoj za sztanga, stopy na szerokosc bioder', 'Chwyć sztange szerzej niz kolana', 'Wypnij klatke, napnij brzuch', 'Wypchnij biodra do przodu stajac prosto'],
   false, NULL),
  ('row', 'Barbell Row', 'pull', 'Gorna czesc plecow', 'Sztanga', 'intermediate',
   ARRAY['Pochyl tułowiidol do przodu z prostymi plecami', 'Przyciągaj sztange do brzucha', 'Sciskaj lopatki na gorze', 'Opuszczaj kontrolowany'],
   false, NULL),
  ('cable-row', 'Cable Row', 'pull', 'Srodkowa czesc plecow', 'Wyciąg', 'beginner',
   ARRAY['Usiasdz prosto, stopy na stopniach', 'Przyciągaj uchwyty do brzucha', 'Sciskaj lopatki na gorze', 'Opuszczaj kontrolowany'],
   false, NULL),
  ('pullup', 'Pull-up', 'pull', 'Latosy', 'Drazek', 'advanced',
   ARRAY['Chwyć drazek szerokim chwytem', 'Przyciągaj sie az podbrodek bedzie nad drazkiem', 'Opuszczaj kontrolowany do pelnego wyprostu'],
   false, NULL),
  ('lat-pd', 'Lat Pulldown', 'pull', 'Latosy', 'Wyciąg', 'beginner',
   ARRAY['Usiasdz pod maszyna, chwyć szeroko', 'Przyciągaj uchwyty do gornej czesci klatki', 'Opuszczaj kontrolowany'],
   false, NULL),
  ('curl', 'Barbell Curl', 'pull', 'Bicepsy', 'Sztanga', 'beginner',
   ARRAY['Stoj prosto, sztanga przed biodrami', 'Przyciągaj sztaze do barkow', 'Nie bujaj tułowiem', 'Opuszczaj kontrolowany'],
   false, NULL),
  ('face-pull', 'Face Pull', 'pull', 'Tylna czesc barkow', 'Wyciąg', 'beginner',
   ARRAY['Ustaw wycig na wysokosci twarzy', 'Przyciągaj linki do twarzy', 'Rozszerzaj lopatki', 'Opuszczaj kontrolowany'],
   false, NULL),
  ('plank', 'Plank', 'core', 'Core', 'Wlasne cialo', 'beginner',
   ARRAY['Podpieraj sie na przedramionach i palcach stop', 'Utrzymuj prosta linie ciala', 'Napnij brzuch i posladki'],
   false, NULL),
  ('ab-rollout', 'Ab Rollout', 'core', 'Core', 'Kolko do brzuszkow', 'intermediate',
   ARRAY['Klęcz na podlodze z kolkem', 'Przewalaj kolko do przodu', 'Wroc do pozycji poczatkowej'],
   false, NULL),
  ('cable-crunch', 'Cable Crunch', 'core', 'Core', 'Wyciąg', 'beginner',
   ARRAY['Klęcz przodem do wyciagu', 'Przyciągaj uchwyty do kolan', 'Skracaj odleglosc miedzy zebrem a biodrem'],
   false, NULL)
ON CONFLICT (id) DO NOTHING;
